export default
[ { question: 'What is the difference between a hot and cold bed?',
    answer: 'Cold bed: All of your sheets and belongings in the vicinity of the bed remain put throughout the lease. No one sleeps in your bed, except you. We only have cold beds. Hot bed: Sheets and all belongings in the vicinity of the bed are removed when you are away from the apartment. Beds are assigned on a first come basis so you and others will sleep in different beds each stay. We do not offer hot beds as it tends to be more disruptive, crowded and noisy.',
    tags: 'hot, cold, bed',
    cat: 'General',
    rank: '' },
  { question: 'How do I get to / from the SFO airport?',
    answer: 'Driving to the airport takes under 10 minutes with no traffic from the pad. Uber/Lyft are $9-15 depending on usage and traffic. Two shuttles operate near the complex. Search \'shuttle\' for more info',
    tags: 'directions, to the apartment, from the apartment, location',
    cat: 'Transportation',
    rank: '' },
  { question: 'Can I receive mail or packages at the crashpad?',
    answer: 'Yes! Before sending your package, please review the instructions for sending mail. Failure to address your package correctly could lead to a delayed, returned or lost package.',
    tags: 'mail, packages',
    cat: 'Amenities',
    rank: '' },
  { question: 'Where is the gym / fitness center?',
    answer: 'The gym is located on the first floor of the leasing office, address 1080 Carolan Ave. *Enter the gym through the pool area * Do not go upstairs.',
    tags: 'work out',
    cat: 'Amenities',
    rank: '' },
  { question: 'When does the cleaning lady come?',
    answer: 'The cleaning lady comes Mondays and Fridays between 9 am and 2pm. ST & DSF are deep cleaned Monday with Friday trash pickup. ZO & WF are reversed with Friday deep cleaning and Monday trash pick up.',
    tags: 'cleaning, clean',
    cat: 'General',
    rank: '' },
  { question: 'What do I do if I forgot my building key?',
    answer: 'At the front of each building is a call box that you can call someone to get buzzed in. It varies whose name you search for depending on the apartment. Press call after you find the correct name for your pad: Sunny Tulip, search for Tsybulnik, Dasha. Zen Orchid: search for Palacios, Victor. Dancing Sunflower: search for Shinn, Austin. Wild Flower, search for Williams, Jeffry. If no one answers, post in the FB group.',
    tags: 'forgot, building, key',
    cat: 'General',
    rank: '' },
  { question: 'Do we bring our own towels and bedding?',
    answer: 'Yes. We do not supply any bedding or towels. ',
    tags: 'towels, bedding, bring',
    cat: 'General',
    rank: '' },
  { question: 'How far is the apartment from the airport?',
    answer: 'The apartment is 7ish minutes by car. The name of the complex is Northpark Apartments. All of the apartments we offer are located somewhere in that complex. The address to the main office (for googling purposes) is 1080 Carolan Ave Burlingame CA 94010.',
    tags: 'location, directions',
    cat: 'Transportation',
    rank: '' },
  { question: 'Are there any stores in the area?',
    answer: 'Broadway Ave is about 8 min by foot. You’ll find a Walgreens, a supermarket called Farmer’s Market, along with many shops and restaurants. If you walk to Burlingame Ave (about 20min), you\'ll have a large selections of restaurants, shops, Apple store, and two large supermarkets, Safeway and Mollie.',
    tags: 'location, directions, stores, food, grocery, groceries',
    cat: 'General',
    rank: '' },
  { question: 'How much space are we given for our stuff?',
    answer: 'Everyone gets the following: a toiletries bin, a dry goods bin, a fridge bin, and an underbed bin. There is space to hang your towel in the bathroom and for some shoes at the entrance. There will be closet space as well to hang some clothing. Depending on which room, this could be either in a closet or a wardrobe closet. Some rooms come with an additional drawer in a piece of furniture or a storgage cube. ',
    tags: 'space, bins, shoes, stuff, closet, food, fridge, clothes',
    cat: 'General',
    rank: '' },
  { question: 'Can I apply my deposit to the last month of rent?',
    answer: 'No. Deposit will be held until keys are returned and cannot be applied towards rent. ',
    tags: 'rent, deposit, keys',
    cat: 'Payments',
    rank: '' },
  { question: 'Where do I park? Is it easy to find parking?',
    answer: 'A private parking space is $60 per month, but there\'s usually a waiting list  so let us know ASAP if you are interested. Free street parking is on Carolan Ave, Cadillac Ave, Rollins Rd, and in the neighborhood off Toyon Dr. Double check any signs! In some places parking is not permitted after certain hours or parking not permitted over 2 hours after 10am. The parking lot in front of the office is not allowed to be used for overnight parking ever.',
    tags: 'parking, car',
    cat: 'Amenities',
    rank: '' },
  { question: 'Is the crashpad co-ed? (mixed gender bedrooms)',
    answer: 'The apartments are all co-ed. We have several rooms that are female only. Let us know if this is something you are interested in.',
    tags: 'people, beds, bunks, co-ed',
    cat: 'General',
    rank: '' },
  { question: 'How many people live in the apartment? How many people per room?',
    answer: 'There are 18 people per apartment. Per room there are 8, 6, and 4 people.',
    tags: 'people, beds, bunks, co-ed',
    cat: 'General',
    rank: '' },
  { question: 'How many bedrooms / bathrooms are there?',
    answer: 'There are 3 bedrooms and 2 full bathrooms.',
    tags: 'people, room, bathroom, rooms, bathrooms',
    cat: 'General',
    rank: '' },
  { question: 'What do we need to bring?',
    answer: 'Bring twin size sheets, towels, and pillows. The kitchen is fully stocked with dishes, etc for your use. Coffee, rice, and oatmeal are provided free of charge, along with dryer sheets and laundry detergent.',
    tags: 'sheets, towels, ',
    cat: 'General',
    rank: '' },
  { question: 'Are the beds bunk beds?',
    answer: 'Yes. All beds are bunk beds. They are on a first come basis, with priority given to current tenants.',
    tags: 'people, beds, bunks',
    cat: 'General',
    rank: '' },
  { question: 'When is the first month of rent due?',
    answer: 'First month of rent is due the day you move in. Please check in for the prorated amount due.',
    tags: 'Rent, prorate, ',
    cat: 'General',
    rank: '' },
  { question: 'Is there a shuttle or bus service to get to and from the airport?',
    answer: '[Crown Plaza SFO](https://goo.gl/maps/X8DYDNUx9Q32) is every 15 min and closest. [Holiday Inn Airport](https://goo.gl/maps/rrDGgW8f9p82) is every 30 min and you CANNOT be in uniform. It takes the shuttles about 8 minutes to get to T1 and 14 minutes to farthest international terminal.',
    tags: 'directions, to the apartment, from the apartment, location, bus, shuttle',
    cat: 'Transportation',
    rank: '' },
  { question: 'How much is deposit? When will it be returned?',
    answer: 'Deposit is $100 and will be returned after move out, with 30 days notice, once all keys are returned.',
    tags: 'deposit, keys',
    cat: 'General',
    rank: '' },
  { question: 'What happens if I lost my key / keys?',
    answer: 'We will issue you new keys and there will be a $50 charge taken from your deposit.',
    tags: 'deposit, keys',
    cat: 'General',
    rank: '' },
  { question: 'What\'s up with the food on the front of the dining table?',
    answer: 'It\'s for everyone! See something you like? It\'s yours!',
    tags: 'food, table, community',
    cat: 'General',
    rank: '' },
  { question: 'Is there an easy way to get around Burlingame?',
    answer: '[Burlingame Trolley Service](https://burlingamechamber.org/visiting-burlingame/getting-around-town/) runs Monday through Saturday serving both the Burlingame Avenue and Broadway shopping areas and Airport Hotels. [Schedule PDF](https://burlingamechamber.org/wp-content/uploads/2014/04/ShowDocument.pdf)',
    tags: 'trolley',
    cat: 'Transportation',
    rank: '' },
  { question: 'What is move out process?',
    answer: 'Give 30 days notice, confirm move out once keys are returned and bed / bins are empty. Deposit will be returned only after keys have been returned.',
    tags: '',
    cat: 'Respsonsibilies',
    rank: '' },
  { question: 'Where do we empty out the trash?',
    answer: 'Trash chutes are located on the north stairway (except Sunny Tulip where it is South). There\'s a square metal door in the wall that drops into the dumpster.',
    tags: '',
    cat: 'General',
    rank: '' },
  { question: 'When is rent due? How much is the late fee?',
    answer: 'Rent is due on the 1st of each month. Rent is considered late if not received on or before the 3rd of each month. There is a $5 fee for each date rent is late.',
    tags: '',
    cat: 'Payments',
    rank: '' },
  { question: 'How can I pay rent?',
    answer: 'Venmo, Cash app, PayPal, Zelle, Check, Bitcoin, Ethereum are all accepted. Cash payments are allowed by request only.',
    tags: '',
    cat: 'Payments',
    rank: '' },
  { question: 'Do I need to bring sheets, towels or pillows?',
    answer: 'Yes. You will provide almost everything you need. We provide toilet paper, hand/dish soap, laundry detergent, dryer sheets, disinfectant wipes, oatmeal, rice, coffee, paper towels and occasionally other goodies.',
    tags: '',
    cat: 'General',
    rank: '' },
  { question: 'How many storage bins will we get?',
    answer: 'Everyone gets the following: a toiletries bin, a dry goods bin, a fridge bin, and an underbed bin. There is space to hang your towel in the bathroom and for some shoes at the entrance. There will be closet space as well to hang some clothing. Depending on which room, this could be either in a closet or a wardrobe closet. Some rooms come with an additional drawer in a piece of furniture or a storgage cube. ',
    tags: '',
    cat: 'General',
    rank: '' },
  { question: 'Where can I put my bicycle? Will my bike get stolen?',
    answer: 'For shiny, nice bicycles, we offer in-crashpad storage on wall for $20 per month. For commuter bicycles, a high quality U-lock should be sufficient. However, bike theft is common in the Bay Area and no lock is 100%.',
    tags: '',
    cat: 'Transportation',
    rank: '' },
  { question: 'What are good restaurants in the area?',
    answer: 'Maverick Jack\'s ([GMap](https://goo.gl/maps/1ZJ3Xbj96DE2) / [Menu](http://www.maverickjacks.com/menus/)) has good, locally-sourced burgers and $10 Tuesday special. Bonne Sante has huge sandwiches that are good, but not gourmet by any means. Que SeRaw SeRaw has counter service small vegan bites and desserts. Mingalaba does Burmese food justice. Rasoi has some great Indian flavors. Limon Rotisserie slangs some damn fine chicken, but $28 / whole chicken breaks the bank a little.',
    tags: '',
    cat: 'Amenities',
    rank: '' },
  { question: 'Can I submit an official USPS change of address form?',
    answer: 'No. Please do not officially change your address to the crashpad. The tiny mailbox would literally explode if just a few people did this.',
    tags: '',
    cat: 'Respsonsibilies',
    rank: '' },
  { question: 'Can my friend sleep on couch or in my bed?',
    answer: 'To maintain a comfortable living area for everyone, no one is ever allowed to sleep on the couch. You are the only person allowed to sleep in your bed. Friends can visit the pad, but this is subject to availability and express prior approval.',
    tags: '',
    cat: 'General',
    rank: '' },
  { question: 'Where is the nearest BART?',
    answer: '[Milbrae BART station](https://goo.gl/maps/aCJMVCStp112) ([schedule](https://www.bart.gov/stations/mlbr/schedule) is 1.8 miles north via California Dr. CalTrain available at [Burlingame Station](https://goo.gl/maps/jCtKc1RYobx) and [Broadway Station](https://goo.gl/maps/Zpab8j6KZKw) on weekends only.',
    tags: '',
    cat: 'Transportation',
    rank: '' },
  { question: 'Is there a pool? Spa / hot tub / Jacuzzi?',
    answer: 'Yes. There are two large pools in the complex and one large hot tub.',
    tags: '',
    cat: 'Amenities',
    rank: '' },
  { question: 'Can I talk to the leasing office / apartment management?',
    answer: 'Since your name isn\'t listed on the lease, you aren\'t an official resident and cannot speak with office staff as a resident! Please do not go to the office or talk to management in regards to the apartment!',
    tags: '',
    cat: 'Respsonsibilies',
    rank: '' },
  { question: 'How do we do laundry? Is there a laundromat nearby?',
    answer: 'There is a waasher and dryer at the apartment. We provide free laundry detergent and dryer sheets.',
    tags: '',
    cat: 'Amenities',
    rank: '' },
  { question: 'Am I required to do chores or deep cleaning?',
    answer: 'We do not require any serious cleaning from our residents. The crashpad is for when you are done with work. We ask you to do all your own dishes and keep all your belongings tidy, but you\'ll never be scrubbing a toilet bowl or bath tub!',
    tags: '',
    cat: 'Amenities',
    rank: '' },
  { question: 'How much is rent? When is it due?',
    answer: 'Rent is $375 and is due on the first of every month. The grace period for rent extends through the 3rd. Rent paid on the 4th of the month is considered late and will be assessed at $5 per day late fee.',
    tags: '',
    cat: 'General',
    rank: '' },
  { question: 'Do I have to sign a lease? Is there a contract?',
    answer: 'You do not have to sign a lease and no credit check will be done. We do ask you sign a contract that requires 30 day move-out notice to receive your entire refundable deposit back. This is a month-to-month arrangement.',
    tags: '',
    cat: 'General',
    rank: '' },
  { question: 'Where is the nearest CalTrain station?',
    answer: 'CalTrain available at [Burlingame Station](https://goo.gl/maps/jCtKc1RYobx) and [Broadway Station](https://goo.gl/maps/Zpab8j6KZKw) on weekends only.',
    tags: '',
    cat: 'Transportation',
    rank: '' },
  { question: 'I have a comment, complaint, suggestion or issue.',
    answer: 'Let us know! We love all feedback good or bad. Even though we feel we do a great job, we are always trying to improve!',
    tags: '',
    cat: 'General',
    rank: '' } ]
;
